#!/bin/zsh

GIT_CMDS=("branch" "br"  "checkout" "co" "status" "st"  "pull"  "fetch" "remote")
CWD=`pwd`

function println() {
    RED='\033[01;31m'
    GREEN='\033[01;32m'
    YELLOW='\033[01;33m'
    BLUE='\033[01;34m'
    NONE='\033[0m'
    echo "$1" | awk -v y=$YELLOW -v n=$NONE -F '/' '{print "\n>>>>> " y$(NF-1)n}'
}

function gitcmd() {
    echo $CWD
    for dir in `find $CWD -name ".git" | awk -F '.' '{print $1}'`; do
        cd $dir
        println $dir    
        git $@    
    done
}

function test1() {
    if [[ -v APPS ]]
    then
        echo "1"
    else
        echo "2"
    fi
}

function shot() {
    adb shell dumpsys SurfaceFlinger --display-id
    if [ -z "$APPS" ]
    then
        adb exec-out screencap -d 14030544112329034 -p > $CWD/$1.png
        open $CWD/$1.png
    else
        adb exec-out screencap -d 14030544112329034 -p > $APPS/data/shots/$1.png
        open $APPS/data/shots/
        open $APPS/data/shots/$1.png
    fi
}

function conn() {
    sudo ifconfig vlan1 create
    sudo ifconfig vlan1 vlan 1 vlandev en5
    sudo ifconfig vlan1 192.168.1.99
    #adb kill-server
    adb connect 192.168.1.12
    adb devices
}

function help() {
    echo ">>>>>>HELP>>>>>>
Git:
    fetch, pull, branch, status, check, remote.
        Eg. # lu branch -v 
            will list all local branches of every $APP git repositories on your terminal.
Test:
    shot [photoName]
        To take a screen shot from CID screen, and save as [photoName].png in your computer
    conn
        This is an encapsulation of adb commands connecting to CCCv1 or CCCv2.
<<<<<<HELP<<<<<<
"
}

for cmd in ${GIT_CMDS[*]}; do
    if [ "$cmd" = "$1" ]; then        
        gitcmd $@
        exit
    fi
done

if [ $# -eq 0 ]
then
    help
fi

$@

----- README.md -----
This is a simple script tool like Google REPO. If you feel struggle to use multiple Git projects at the same time on terminal, you can try this. 

For example, you are on ~/../apps/ directory which contains several git projects, and you can use '$luc branch -v' exactly like 
'$git branch -v' on terminal to show branches information on all git repos under this folder ~/../apps/.

Because the output of this script will be std and it can be cooperate with [piplines](https://www.gnu.org/software/bash/manual/html_node/Pipelines.html). For example, I can use 
```shell
~/../apps $ luc st | grep "\-lib" -A 10
```
to list all changes from these projects for me:
```shell
>>>>> luc-i18n-lib
>>>>> luc-cloud-lib
>>>>> luc-settings-lib
...
```

### Install
``` sh
export LUC=$(mktemp /tmp/luc.XXXXXXXXX)
curl -o ${LUC} https://gitlab.corp.atieva.com/shengwang/scripts/lu
install -m 755 ${LUC} ~/bin/luc
```

### Usage
```shell
~/../apps $ luc
>>>>>>HELP>>>>>>
Git:
    remote, fetch, pull, branch (br), status (st), checkout (co).
        Eg. # luc branch -v 
            will list all local branches of every git repositories on your terminal on the folder you executed.
Test:
    shot [photoName]
        To take a screen shot from CID screen, and save as [photoName].png in your computer
    conn
        This is an encapsulation of adb commands connecting to CCCv1 or CCCv2.
<<<<<<HELP<<<<<<
```



