#!/usr/local/bin/python3

import sys
import operator
import re
import os
import collections
import time

def pendingList():
    print("pendingList")

def main():
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument('-pending', action='store_true',  help="listing all pending works")
    args = parser.parse_args()
    if args.pending:
        pendingList()

if __name__ == "__main__":
    main()

